In [1]:
import pandas as pd
import numpy as np
import time
import os
import io
from PIL import Image
import matplotlib.pyplot as plt
import pickle
from datetime import timedelta

In [2]:
file_dir = "../Processed_Gases_Official_Data/"
Delhi_Stations_name = []
for x in os.listdir(file_dir):
    if "Delhi_" in x:
        Delhi_Stations_name.append(x)

In [3]:
Delhi_Stations_name

['Delhi_Delhi_Alipur, Delhi - DPCC.csv',
 'Delhi_Delhi_Anand Vihar, Delhi - DPCC.csv',
 'Delhi_Delhi_Ashok Vihar, Delhi - DPCC.csv',
 'Delhi_Delhi_Aya Nagar, Delhi - IMD.csv',
 'Delhi_Delhi_Bawana, Delhi - DPCC.csv',
 'Delhi_Delhi_Burari Crossing, Delhi - IMD.csv',
 'Delhi_Delhi_Chandni Chowk, Delhi - IITM.csv',
 'Delhi_Delhi_CRRI Mathura Road, Delhi - IMD.csv',
 'Delhi_Delhi_Dr. Karni Singh Shooting Range, Delhi - DPCC.csv',
 'Delhi_Delhi_DTU, Delhi - CPCB.csv',
 'Delhi_Delhi_Dwarka-Sector 8, Delhi - DPCC .csv',
 'Delhi_Delhi_East Arjun Nagar, Delhi - CPCB.csv',
 'Delhi_Delhi_IGI Airport (T3), Delhi - IMD.csv',
 'Delhi_Delhi_IHBAS, Dilshad Garden, Delhi - CPCB.csv',
 'Delhi_Delhi_ITO, Delhi - CPCB.csv',
 'Delhi_Delhi_Jahangirpuri, Delhi - DPCC.csv',
 'Delhi_Delhi_Jawaharlal Nehru Stadium, Delhi - DPCC.csv',
 'Delhi_Delhi_Lodhi Road, Delhi - IITM.csv',
 'Delhi_Delhi_Lodhi Road, Delhi - IMD.csv',
 'Delhi_Delhi_Major Dhyan Chand National Stadium, Delhi - DPCC.csv',
 'Delhi_Delhi_Mandir Marg, Delhi - DPCC.csv',
 'Delhi_Delhi_Mundka, Delhi - DPCC.csv',
 'Delhi_Delhi_Najafgarh, Delhi - DPCC.csv',
 'Delhi_Delhi_Narela, Delhi - DPCC.csv',
 'Delhi_Delhi_Nehru Nagar, Delhi - DPCC.csv',
 'Delhi_Delhi_North Campus, DU, Delhi - IMD.csv',
 'Delhi_Delhi_NSIT Dwarka, Delhi - CPCB.csv',
 'Delhi_Delhi_Okhla Phase-2, Delhi - DPCC.csv',
 'Delhi_Delhi_Patparganj, Delhi - DPCC.csv',
 'Delhi_Delhi_Punjabi Bagh, Delhi - DPCC.csv',
 'Delhi_Delhi_Pusa, Delhi - DPCC.csv',
 'Delhi_Delhi_Pusa, Delhi - IMD.csv',
 'Delhi_Delhi_R K Puram, Delhi - DPCC.csv',
 'Delhi_Delhi_Rohini, Delhi - DPCC.csv',
 'Delhi_Delhi_Shadipur, Delhi - CPCB.csv',
 'Delhi_Delhi_Sirifort, Delhi - CPCB.csv',
 'Delhi_Delhi_Sonia Vihar, Delhi - DPCC.csv',
 'Delhi_Delhi_Sri Aurobindo Marg, Delhi - DPCC.csv',
 'Delhi_Delhi_Vivek Vihar, Delhi - DPCC.csv',
 'Delhi_Delhi_Wazirpur, Delhi - DPCC.csv']

In [4]:
pd.read_csv(file_dir + Delhi_Stations_name[0], index_col=0)

             From_Date           To_Date  PM2.5   SO2    NO2    CO
0     01-01-2018 00:00  02-01-2018 00:00    NaN   NaN    NaN   NaN
1     02-01-2018 00:00  03-01-2018 00:00    NaN   NaN    NaN   NaN
2     03-01-2018 00:00  04-01-2018 00:00    NaN   NaN    NaN   NaN
3     04-01-2018 00:00  05-01-2018 00:00    NaN   NaN    NaN   NaN
4     05-01-2018 00:00  06-01-2018 00:00    NaN   NaN    NaN   NaN
...                ...               ...    ...   ...    ...   ...
1691  19-08-2022 00:00  20-08-2022 00:00  19.06  4.81  10.15  0.58
1692  20-08-2022 00:00  21-08-2022 00:00  31.54  3.91  10.69  0.59
1693  21-08-2022 00:00  22-08-2022 00:00  45.42  4.79  12.35  0.57
1694  22-08-2022 00:00  23-08-2022 00:00  28.53  3.24   7.47  0.48
1695  23-08-2022 00:00  23-08-2022 14:18  27.57  4.25   4.22  0.37

[1696 rows x 6 columns]

In [5]:
coods = pd.read_csv("../station_coordinates.csv", index_col = 0)
coods

                                               Station  Longitude   Latitude
0    Andhra Pradesh_Vijayawada_PWD Grounds, Vijayaw...  80.631355  16.506194
1    Andhra Pradesh_Visakhapatnam_GVM Corporation, ...  83.218481  17.686816
2    Bihar_Aurangabad_Gurdeo Nagar, Aurangabad - BSPCB  84.368005  24.754865
3        Bihar_Patna_DRM Office Danapur, Patna - BSPCB  85.044299  25.585624
4    Bihar_Patna_Govt. High School Shikarpur, Patna...  85.227233  25.593270
..                                                 ...        ...        ...
178   West Bengal_Kolkata_Bidhannagar, Kolkata - WBPCB  88.414312  22.579684
179  West Bengal_Kolkata_Fort William, Kolkata - WBPCB  88.336076  22.554688
180      West Bengal_Kolkata_Jadavpur, Kolkata - WBPCB  88.370901  22.495499
181  West Bengal_Kolkata_Rabindra Bharati Universit...  88.359384  22.584454
182      West Bengal_Kolkata_Victoria, Kolkata - WBPCB  88.342558  22.544808

[183 rows x 3 columns]

In [6]:
Delhi_Stations_Coods = coods[coods["Station"].str.contains(", Delhi")]
Delhi_Stations_Coods

                                              Station  Longitude   Latitude
12                   Delhi_Delhi_Alipur, Delhi - DPCC  77.133136  28.797226
13              Delhi_Delhi_Anand Vihar, Delhi - DPCC  77.302706  28.650218
14              Delhi_Delhi_Ashok Vihar, Delhi - DPCC  77.176524  28.690979
15                 Delhi_Delhi_Aya Nagar, Delhi - IMD  77.132942  28.472044
16                   Delhi_Delhi_Bawana, Delhi - DPCC  77.048335  28.793229
17           Delhi_Delhi_Burari Crossing, Delhi - IMD  77.197380  28.728500
18            Delhi_Delhi_Chandni Chowk, Delhi - IITM  77.230337  28.650533
19         Delhi_Delhi_CRRI Mathura Road, Delhi - IMD  77.275034  28.551720
20  Delhi_Delhi_Dr. Karni Singh Shooting Range, De...  77.267095  28.499727
21                      Delhi_Delhi_DTU, Delhi - CPCB  77.118314  28.749987
22         Delhi_Delhi_Dwarka-Sector 8, Delhi - DPCC   77.070837  28.572038
23         Delhi_Delhi_East Arjun Nagar, Delhi - CPCB  77.294747  28.656173
24          Delhi_Delhi_IGI Airport (T3), Delhi - IMD  77.084401  28.555084
25    Delhi_Delhi_IHBAS, Dilshad Garden, Delhi - CPCB  77.304953  28.682627
26                      Delhi_Delhi_ITO, Delhi - CPCB  77.250573  28.630829
27             Delhi_Delhi_Jahangirpuri, Delhi - DPCC  77.166631  28.729617
28  Delhi_Delhi_Jawaharlal Nehru Stadium, Delhi - ...  77.233330  28.583305
29               Delhi_Delhi_Lodhi Road, Delhi - IITM  77.228079  28.591063
30                Delhi_Delhi_Lodhi Road, Delhi - IMD  77.228079  28.591063
31  Delhi_Delhi_Major Dhyan Chand National Stadium...  77.236798  28.612569
32              Delhi_Delhi_Mandir Marg, Delhi - DPCC  77.200475  28.634175
33                   Delhi_Delhi_Mundka, Delhi - DPCC  77.034937  28.682314
34                Delhi_Delhi_Najafgarh, Delhi - DPCC  76.985453  28.609013
35                   Delhi_Delhi_Narela, Delhi - DPCC  77.089215  28.854882
36              Delhi_Delhi_Nehru Nagar, Delhi - DPCC  77.250573  28.570604
37          Delhi_Delhi_North Campus, DU, Delhi - IMD  77.210336  28.687193
38              Delhi_Delhi_NSIT Dwarka, Delhi - CPCB  77.037965  28.610022
39            Delhi_Delhi_Okhla Phase-2, Delhi - DPCC  77.276433  28.535763
40               Delhi_Delhi_Patparganj, Delhi - DPCC  77.304571  28.634731
41             Delhi_Delhi_Punjabi Bagh, Delhi - DPCC  77.128476  28.670693
42                     Delhi_Delhi_Pusa, Delhi - DPCC  77.157144  28.637672
43                      Delhi_Delhi_Pusa, Delhi - IMD  77.157144  28.637672
44                Delhi_Delhi_R K Puram, Delhi - DPCC  77.176744  28.566008
45                   Delhi_Delhi_Rohini, Delhi - DPCC  77.082215  28.738268
46                 Delhi_Delhi_Shadipur, Delhi - CPCB  77.156220  28.651027
47                 Delhi_Delhi_Sirifort, Delhi - CPCB  77.214799  28.550583
48              Delhi_Delhi_Sonia Vihar, Delhi - DPCC  77.249589  28.733247
49       Delhi_Delhi_Sri Aurobindo Marg, Delhi - DPCC  77.206307  28.556222
50              Delhi_Delhi_Vivek Vihar, Delhi - DPCC  77.317654  28.671246
51                 Delhi_Delhi_Wazirpur, Delhi - DPCC  77.160440  28.697544

In [7]:
Station_Values = {}
for name in Delhi_Stations_Coods["Station"]:
    temp = pd.read_csv(file_dir+name+".csv", index_col=0).iloc[:-1]
    temp.set_index('To_Date', inplace=True)
    temp.index = pd.to_datetime(temp.index, format="%d-%m-%Y %H:%S")
    temp = temp.resample('14D').apply(np.mean)
    Station_Values[name] = temp.copy()

In [8]:
import folium
def draw_Circle(loc, radius, map, color):
    folium.Circle(
        location=loc,
        radius=int(radius),
        color=color,
        stroke=False,
        fill=True,
        fill_opacity=0.6,
        opacity=1,
    ).add_to(map)
def draw_cross(loc, map):
    mak = folium.map.Marker(loc, icon=folium.features.CustomIcon(
                                            "https://uxwing.com/wp-content/themes/uxwing/download/checkmark-cross/cross-icon.png", 
                                            icon_size=(10, 10)))
    map.add_child(mak)
def get_concat_h(im1, im2):
    dst = Image.new('RGB', (im1.width + im2.width, im1.height))
    dst.paste(im1, (0, 0))
    dst.paste(im2, (im1.width, 0))
    return dst
def draw_bar(x, max_x, date, type_polution):
    px = 1/plt.rcParams['figure.dpi']  # pixel in inches
    plt.subplots(figsize=(100*px, 600*px))
    plt.title(f"{type_polution}\n{date.date()}\n\n")
    plt.bar(0, x)
    plt.ylim(0, max_x*1.05)
    ax = plt.gca()
    ax.xaxis.set_visible(False)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['bottom'].set_visible(False)
    buf = io.BytesIO()
    plt.savefig(buf, format='png', bbox_inches='tight')
    im = Image.open(buf)
    return im
def draw_star(loc, map):
    mak = folium.map.Marker(loc, icon=folium.features.CustomIcon(
                                            "https://cdn-icons-png.flaticon.com/512/1828/1828884.png", 
                                            icon_size=(30, 30)))
    map.add_child(mak)

In [9]:
API_values = pd.read_csv("../Data_Openweathermap/raw_data/Delhi_raw.csv", index_col = 0)

In [10]:
API_values.set_index(pd.to_datetime(API_values["Date"]), inplace=True)
API_values.rename(columns={"PM2_5": "PM2.5"}, inplace=True)
API_values = API_values.rolling(14).mean()

C:\Users\Deyao Kong\AppData\Local\Temp\ipykernel_54260\2830208390.py:3: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['City', 'Date'], dtype='object')
  API_values = API_values.rolling(14).mean()

In [11]:
API_values

               Lat     Lng           CO        NO2        SO2       PM2.5
Date
2020-11-24     NaN     NaN          NaN        NaN        NaN         NaN
2020-11-25     NaN     NaN          NaN        NaN        NaN         NaN
2020-11-26     NaN     NaN          NaN        NaN        NaN         NaN
2020-11-27     NaN     NaN          NaN        NaN        NaN         NaN
2020-11-28     NaN     NaN          NaN        NaN        NaN         NaN
...            ...     ...          ...        ...        ...         ...
2022-07-21  28.564  77.145  1974.920702  64.884371  85.945281  146.165940
2022-07-22  28.564  77.145  2025.584630  66.132764  88.898584  149.153767
2022-07-23  28.564  77.145  2013.504779  65.610055  87.670340  146.113261
2022-07-24  28.564  77.145  2003.073975  65.265918  87.349656  144.544779
2022-07-25  28.564  77.145  1960.297725  62.627615  84.006084  140.782666

[608 rows x 6 columns]

In [12]:
scale = {}
for type_polution in ["CO", "NO2", "SO2", "PM2.5"]:
    scale[type_polution] = 2000/np.nanmean([x[type_polution].mean() for x in Station_Values.values()])

In [13]:
def draw_gif(type_polution, color, prefix=""):
    m = folium.Map(location=[28.65, 77.15])
    list_img = []
    max_polution = API_values[type_polution].max()
    indexes = list(Station_Values.values())[0].index
    for date in indexes:
        print(type_polution, date.date(), "{}/{}".format((len(list_img)+1), len(indexes)))
        m = folium.Map(location=[28.65, 77.15], zoom_start=10)
        draw_star([28.564, 77.145], m)
        for _, row in Delhi_Stations_Coods.iterrows():
            try:
                value = Station_Values[row["Station"]].loc[date][type_polution]
            except:
                value = np.nan

            cood = row[["Latitude", "Longitude"]].to_list()
            if np.isnan(value):
                draw_cross(cood, m)
            else:
                draw_Circle(cood, value*scale[type_polution], m, color)
        if date in API_values.index:
            api_value = API_values[type_polution].loc[date]
        else:
            api_value = 0
        api_bar = draw_bar(api_value, max_polution, date, type_polution)
        img_data = m._to_png()
        list_img.append(get_concat_h(api_bar, Image.open(io.BytesIO(img_data)).crop((400, 100, 1000, 700))))
        plt.close()
    if prefix:
        prefix += "_"
    list_img[0].save(f'{prefix}{type_polution}.gif', save_all=True, append_images=list_img[1:], duration=100)
    with open(f"{prefix}{type_polution}_gif_data.pkl", "wb") as f:
        pickle.dump(list_img, f)

In [14]:
colors = {}
colors["SO2"] = "#5e312d"
colors["CO"] = "#807c1f"
colors["PM2.5"] = "#3d3d35"
colors["NO2"] = "#415073"

In [15]:
%matplotlib agg

for type_polution in ["CO", "NO2", "SO2", "PM2.5"]:
    start_time = time.time()
    print(type_polution, "started")
    
    draw_gif(type_polution, colors[type_polution])
    
    end_time = time.time()
    print(type_polution, "finished, time used:", str(timedelta(seconds=int(end_time-start_time))))
    print("#"*30)

CO started
CO 2018-01-02 1/122
CO 2018-01-16 2/122
CO 2018-01-30 3/122
CO 2018-02-13 4/122
CO 2018-02-27 5/122
CO 2018-03-13 6/122
CO 2018-03-27 7/122
CO 2018-04-10 8/122
CO 2018-04-24 9/122
CO 2018-05-08 10/122
CO 2018-05-22 11/122
CO 2018-06-05 12/122
CO 2018-06-19 13/122
CO 2018-07-03 14/122
CO 2018-07-17 15/122
CO 2018-07-31 16/122
CO 2018-08-14 17/122
CO 2018-08-28 18/122
CO 2018-09-11 19/122
CO 2018-09-25 20/122
CO 2018-10-09 21/122
CO 2018-10-23 22/122
CO 2018-11-06 23/122
CO 2018-11-20 24/122
CO 2018-12-04 25/122
CO 2018-12-18 26/122
CO 2019-01-01 27/122
CO 2019-01-15 28/122
CO 2019-01-29 29/122
CO 2019-02-12 30/122
CO 2019-02-26 31/122
CO 2019-03-12 32/122
CO 2019-03-26 33/122
CO 2019-04-09 34/122
CO 2019-04-23 35/122
CO 2019-05-07 36/122
CO 2019-05-21 37/122
CO 2019-06-04 38/122
CO 2019-06-18 39/122
CO 2019-07-02 40/122
CO 2019-07-16 41/122
CO 2019-07-30 42/122
CO 2019-08-13 43/122
CO 2019-08-27 44/122
CO 2019-09-10 45/122
CO 2019-09-24 46/122
CO 2019-10-08 47/122
CO 2019-10-22 48/122
CO 2019-11-05 49/122
CO 2019-11-19 50/122
CO 2019-12-03 51/122
CO 2019-12-17 52/122
CO 2019-12-31 53/122
CO 2020-01-14 54/122
CO 2020-01-28 55/122
CO 2020-02-11 56/122
CO 2020-02-25 57/122
CO 2020-03-10 58/122
CO 2020-03-24 59/122
CO 2020-04-07 60/122
CO 2020-04-21 61/122
CO 2020-05-05 62/122
CO 2020-05-19 63/122
CO 2020-06-02 64/122
CO 2020-06-16 65/122
CO 2020-06-30 66/122
CO 2020-07-14 67/122
CO 2020-07-28 68/122
CO 2020-08-11 69/122
CO 2020-08-25 70/122
CO 2020-09-08 71/122
CO 2020-09-22 72/122
CO 2020-10-06 73/122
CO 2020-10-20 74/122
CO 2020-11-03 75/122
CO 2020-11-17 76/122
CO 2020-12-01 77/122
CO 2020-12-15 78/122
CO 2020-12-29 79/122
CO 2021-01-12 80/122
CO 2021-01-26 81/122
CO 2021-02-09 82/122
CO 2021-02-23 83/122
CO 2021-03-09 84/122
CO 2021-03-23 85/122
CO 2021-04-06 86/122
CO 2021-04-20 87/122
CO 2021-05-04 88/122
CO 2021-05-18 89/122
CO 2021-06-01 90/122
CO 2021-06-15 91/122
CO 2021-06-29 92/122
CO 2021-07-13 93/122
CO 2021-07-27 94/122
CO 2021-08-10 95/122
CO 2021-08-24 96/122
CO 2021-09-07 97/122
CO 2021-09-21 98/122
CO 2021-10-05 99/122
CO 2021-10-19 100/122
CO 2021-11-02 101/122
CO 2021-11-16 102/122
CO 2021-11-30 103/122
CO 2021-12-14 104/122
CO 2021-12-28 105/122
CO 2022-01-11 106/122
CO 2022-01-25 107/122
CO 2022-02-08 108/122
CO 2022-02-22 109/122
CO 2022-03-08 110/122
CO 2022-03-22 111/122
CO 2022-04-05 112/122
CO 2022-04-19 113/122
CO 2022-05-03 114/122
CO 2022-05-17 115/122
CO 2022-05-31 116/122
CO 2022-06-14 117/122
CO 2022-06-28 118/122
CO 2022-07-12 119/122
CO 2022-07-26 120/122
CO 2022-08-09 121/122
CO 2022-08-23 122/122
CO finished, time used: 0:18:01
##############################
NO2 started
NO2 2018-01-02 1/122
NO2 2018-01-16 2/122
NO2 2018-01-30 3/122
NO2 2018-02-13 4/122
NO2 2018-02-27 5/122
NO2 2018-03-13 6/122
NO2 2018-03-27 7/122
NO2 2018-04-10 8/122
NO2 2018-04-24 9/122
NO2 2018-05-08 10/122
NO2 2018-05-22 11/122
NO2 2018-06-05 12/122
NO2 2018-06-19 13/122
NO2 2018-07-03 14/122
NO2 2018-07-17 15/122
NO2 2018-07-31 16/122
NO2 2018-08-14 17/122
NO2 2018-08-28 18/122
NO2 2018-09-11 19/122
NO2 2018-09-25 20/122
NO2 2018-10-09 21/122
NO2 2018-10-23 22/122
NO2 2018-11-06 23/122
NO2 2018-11-20 24/122
NO2 2018-12-04 25/122
NO2 2018-12-18 26/122
NO2 2019-01-01 27/122
NO2 2019-01-15 28/122
NO2 2019-01-29 29/122
NO2 2019-02-12 30/122
NO2 2019-02-26 31/122
NO2 2019-03-12 32/122
NO2 2019-03-26 33/122
NO2 2019-04-09 34/122
NO2 2019-04-23 35/122
NO2 2019-05-07 36/122
NO2 2019-05-21 37/122
NO2 2019-06-04 38/122
NO2 2019-06-18 39/122
NO2 2019-07-02 40/122
NO2 2019-07-16 41/122
NO2 2019-07-30 42/122
NO2 2019-08-13 43/122
NO2 2019-08-27 44/122
NO2 2019-09-10 45/122
NO2 2019-09-24 46/122
NO2 2019-10-08 47/122
NO2 2019-10-22 48/122
NO2 2019-11-05 49/122
NO2 2019-11-19 50/122
NO2 2019-12-03 51/122
NO2 2019-12-17 52/122
NO2 2019-12-31 53/122
NO2 2020-01-14 54/122
NO2 2020-01-28 55/122
NO2 2020-02-11 56/122
NO2 2020-02-25 57/122
NO2 2020-03-10 58/122
NO2 2020-03-24 59/122
NO2 2020-04-07 60/122
NO2 2020-04-21 61/122
NO2 2020-05-05 62/122
NO2 2020-05-19 63/122
NO2 2020-06-02 64/122
NO2 2020-06-16 65/122
NO2 2020-06-30 66/122
NO2 2020-07-14 67/122
NO2 2020-07-28 68/122
NO2 2020-08-11 69/122
NO2 2020-08-25 70/122
NO2 2020-09-08 71/122
NO2 2020-09-22 72/122
NO2 2020-10-06 73/122
NO2 2020-10-20 74/122
NO2 2020-11-03 75/122
NO2 2020-11-17 76/122
NO2 2020-12-01 77/122
NO2 2020-12-15 78/122
NO2 2020-12-29 79/122
NO2 2021-01-12 80/122
NO2 2021-01-26 81/122
NO2 2021-02-09 82/122
NO2 2021-02-23 83/122
NO2 2021-03-09 84/122
NO2 2021-03-23 85/122
NO2 2021-04-06 86/122
NO2 2021-04-20 87/122
NO2 2021-05-04 88/122
NO2 2021-05-18 89/122
NO2 2021-06-01 90/122
NO2 2021-06-15 91/122
NO2 2021-06-29 92/122
NO2 2021-07-13 93/122
NO2 2021-07-27 94/122
NO2 2021-08-10 95/122
NO2 2021-08-24 96/122
NO2 2021-09-07 97/122
NO2 2021-09-21 98/122
NO2 2021-10-05 99/122
NO2 2021-10-19 100/122
NO2 2021-11-02 101/122
NO2 2021-11-16 102/122
NO2 2021-11-30 103/122
NO2 2021-12-14 104/122
NO2 2021-12-28 105/122
NO2 2022-01-11 106/122
NO2 2022-01-25 107/122
NO2 2022-02-08 108/122
NO2 2022-02-22 109/122
NO2 2022-03-08 110/122
NO2 2022-03-22 111/122
NO2 2022-04-05 112/122
NO2 2022-04-19 113/122
NO2 2022-05-03 114/122
NO2 2022-05-17 115/122
NO2 2022-05-31 116/122
NO2 2022-06-14 117/122
NO2 2022-06-28 118/122
NO2 2022-07-12 119/122
NO2 2022-07-26 120/122
NO2 2022-08-09 121/122
NO2 2022-08-23 122/122
NO2 finished, time used: 0:16:57
##############################
SO2 started
SO2 2018-01-02 1/122
SO2 2018-01-16 2/122
SO2 2018-01-30 3/122
SO2 2018-02-13 4/122
SO2 2018-02-27 5/122
SO2 2018-03-13 6/122
SO2 2018-03-27 7/122
SO2 2018-04-10 8/122
SO2 2018-04-24 9/122
SO2 2018-05-08 10/122
SO2 2018-05-22 11/122
SO2 2018-06-05 12/122
SO2 2018-06-19 13/122
SO2 2018-07-03 14/122
SO2 2018-07-17 15/122
SO2 2018-07-31 16/122
SO2 2018-08-14 17/122
SO2 2018-08-28 18/122
SO2 2018-09-11 19/122
SO2 2018-09-25 20/122
SO2 2018-10-09 21/122
SO2 2018-10-23 22/122
SO2 2018-11-06 23/122
SO2 2018-11-20 24/122
SO2 2018-12-04 25/122
SO2 2018-12-18 26/122
SO2 2019-01-01 27/122
SO2 2019-01-15 28/122
SO2 2019-01-29 29/122
SO2 2019-02-12 30/122
SO2 2019-02-26 31/122
SO2 2019-03-12 32/122
SO2 2019-03-26 33/122
SO2 2019-04-09 34/122
SO2 2019-04-23 35/122
SO2 2019-05-07 36/122
SO2 2019-05-21 37/122
SO2 2019-06-04 38/122
SO2 2019-06-18 39/122
SO2 2019-07-02 40/122
SO2 2019-07-16 41/122
SO2 2019-07-30 42/122
SO2 2019-08-13 43/122
SO2 2019-08-27 44/122
SO2 2019-09-10 45/122
SO2 2019-09-24 46/122
SO2 2019-10-08 47/122
SO2 2019-10-22 48/122
SO2 2019-11-05 49/122
SO2 2019-11-19 50/122
SO2 2019-12-03 51/122
SO2 2019-12-17 52/122
SO2 2019-12-31 53/122
SO2 2020-01-14 54/122
SO2 2020-01-28 55/122
SO2 2020-02-11 56/122
SO2 2020-02-25 57/122
SO2 2020-03-10 58/122
SO2 2020-03-24 59/122
SO2 2020-04-07 60/122
SO2 2020-04-21 61/122
SO2 2020-05-05 62/122
SO2 2020-05-19 63/122
SO2 2020-06-02 64/122
SO2 2020-06-16 65/122
SO2 2020-06-30 66/122
SO2 2020-07-14 67/122
SO2 2020-07-28 68/122
SO2 2020-08-11 69/122
SO2 2020-08-25 70/122
SO2 2020-09-08 71/122
SO2 2020-09-22 72/122
SO2 2020-10-06 73/122
SO2 2020-10-20 74/122
SO2 2020-11-03 75/122
SO2 2020-11-17 76/122
SO2 2020-12-01 77/122
SO2 2020-12-15 78/122
SO2 2020-12-29 79/122
SO2 2021-01-12 80/122
SO2 2021-01-26 81/122
SO2 2021-02-09 82/122
SO2 2021-02-23 83/122
SO2 2021-03-09 84/122
SO2 2021-03-23 85/122
SO2 2021-04-06 86/122
SO2 2021-04-20 87/122
SO2 2021-05-04 88/122
SO2 2021-05-18 89/122
SO2 2021-06-01 90/122
SO2 2021-06-15 91/122
SO2 2021-06-29 92/122
SO2 2021-07-13 93/122
SO2 2021-07-27 94/122
SO2 2021-08-10 95/122
SO2 2021-08-24 96/122
SO2 2021-09-07 97/122
SO2 2021-09-21 98/122
SO2 2021-10-05 99/122
SO2 2021-10-19 100/122
SO2 2021-11-02 101/122
SO2 2021-11-16 102/122
SO2 2021-11-30 103/122
SO2 2021-12-14 104/122
SO2 2021-12-28 105/122
SO2 2022-01-11 106/122
SO2 2022-01-25 107/122
SO2 2022-02-08 108/122
SO2 2022-02-22 109/122
SO2 2022-03-08 110/122
SO2 2022-03-22 111/122
SO2 2022-04-05 112/122
SO2 2022-04-19 113/122
SO2 2022-05-03 114/122
SO2 2022-05-17 115/122
SO2 2022-05-31 116/122
SO2 2022-06-14 117/122
SO2 2022-06-28 118/122
SO2 2022-07-12 119/122
SO2 2022-07-26 120/122
SO2 2022-08-09 121/122
SO2 2022-08-23 122/122
SO2 finished, time used: 0:16:59
##############################
PM2.5 started
PM2.5 2018-01-02 1/122

PM2.5 2018-01-16 2/122
PM2.5 2018-01-30 3/122
PM2.5 2018-02-13 4/122
PM2.5 2018-02-27 5/122
PM2.5 2018-03-13 6/122
PM2.5 2018-03-27 7/122
PM2.5 2018-04-10 8/122
PM2.5 2018-04-24 9/122
PM2.5 2018-05-08 10/122
PM2.5 2018-05-22 11/122
PM2.5 2018-06-05 12/122
PM2.5 2018-06-19 13/122
PM2.5 2018-07-03 14/122
PM2.5 2018-07-17 15/122
PM2.5 2018-07-31 16/122
PM2.5 2018-08-14 17/122
PM2.5 2018-08-28 18/122
PM2.5 2018-09-11 19/122
PM2.5 2018-09-25 20/122
PM2.5 2018-10-09 21/122
PM2.5 2018-10-23 22/122
PM2.5 2018-11-06 23/122
PM2.5 2018-11-20 24/122
PM2.5 2018-12-04 25/122
PM2.5 2018-12-18 26/122
PM2.5 2019-01-01 27/122
PM2.5 2019-01-15 28/122
PM2.5 2019-01-29 29/122
PM2.5 2019-02-12 30/122
PM2.5 2019-02-26 31/122
PM2.5 2019-03-12 32/122
PM2.5 2019-03-26 33/122
PM2.5 2019-04-09 34/122
PM2.5 2019-04-23 35/122
PM2.5 2019-05-07 36/122
PM2.5 2019-05-21 37/122
PM2.5 2019-06-04 38/122
PM2.5 2019-06-18 39/122
PM2.5 2019-07-02 40/122
PM2.5 2019-07-16 41/122
PM2.5 2019-07-30 42/122
PM2.5 2019-08-13 43/122
PM2.5 2019-08-27 44/122
PM2.5 2019-09-10 45/122
PM2.5 2019-09-24 46/122
PM2.5 2019-10-08 47/122
PM2.5 2019-10-22 48/122
PM2.5 2019-11-05 49/122
PM2.5 2019-11-19 50/122
PM2.5 2019-12-03 51/122
PM2.5 2019-12-17 52/122
PM2.5 2019-12-31 53/122
PM2.5 2020-01-14 54/122
PM2.5 2020-01-28 55/122
PM2.5 2020-02-11 56/122
PM2.5 2020-02-25 57/122
PM2.5 2020-03-10 58/122
PM2.5 2020-03-24 59/122
PM2.5 2020-04-07 60/122
PM2.5 2020-04-21 61/122
PM2.5 2020-05-05 62/122
PM2.5 2020-05-19 63/122
PM2.5 2020-06-02 64/122
PM2.5 2020-06-16 65/122
PM2.5 2020-06-30 66/122
PM2.5 2020-07-14 67/122
PM2.5 2020-07-28 68/122
PM2.5 2020-08-11 69/122
PM2.5 2020-08-25 70/122
PM2.5 2020-09-08 71/122
PM2.5 2020-09-22 72/122
PM2.5 2020-10-06 73/122
PM2.5 2020-10-20 74/122
PM2.5 2020-11-03 75/122
PM2.5 2020-11-17 76/122
PM2.5 2020-12-01 77/122
PM2.5 2020-12-15 78/122
PM2.5 2020-12-29 79/122
PM2.5 2021-01-12 80/122
PM2.5 2021-01-26 81/122
PM2.5 2021-02-09 82/122
PM2.5 2021-02-23 83/122
PM2.5 2021-03-09 84/122
PM2.5 2021-03-23 85/122
PM2.5 2021-04-06 86/122
PM2.5 2021-04-20 87/122
PM2.5 2021-05-04 88/122
PM2.5 2021-05-18 89/122
PM2.5 2021-06-01 90/122
PM2.5 2021-06-15 91/122
PM2.5 2021-06-29 92/122
PM2.5 2021-07-13 93/122
PM2.5 2021-07-27 94/122
PM2.5 2021-08-10 95/122
PM2.5 2021-08-24 96/122
PM2.5 2021-09-07 97/122
PM2.5 2021-09-21 98/122
PM2.5 2021-10-05 99/122
PM2.5 2021-10-19 100/122
PM2.5 2021-11-02 101/122
PM2.5 2021-11-16 102/122
PM2.5 2021-11-30 103/122
PM2.5 2021-12-14 104/122
PM2.5 2021-12-28 105/122
PM2.5 2022-01-11 106/122
PM2.5 2022-01-25 107/122
PM2.5 2022-02-08 108/122
PM2.5 2022-02-22 109/122
PM2.5 2022-03-08 110/122
PM2.5 2022-03-22 111/122
PM2.5 2022-04-05 112/122
PM2.5 2022-04-19 113/122
PM2.5 2022-05-03 114/122
PM2.5 2022-05-17 115/122
PM2.5 2022-05-31 116/122
PM2.5 2022-06-14 117/122
PM2.5 2022-06-28 118/122
PM2.5 2022-07-12 119/122
PM2.5 2022-07-26 120/122
PM2.5 2022-08-09 121/122
PM2.5 2022-08-23 122/122
PM2.5 finished, time used: 0:17:16
##############################

In [16]:
plt.close()